### PR TITLE
Marian issue 641 modal

### PR DESCRIPTION
**Pull request by mmlumba**
References https://github.com/department-of-veterans-affairs/caseflow/issues/641

**Screenshots for the modals:**
Certification:
screen shot 2017-02-03 at 2 38 10 pm
screen shot 2017-02-03 at 2 38 36 pm
screen shot 2017-02-03 at 2 38 46 pm
screen shot 2017-02-03 at 2 39 17 pm

Efolder Express:
screen shot 2017-02-03 at 2 40 06 pm

If these screenshots look good then I will make PRs to add the HTML/JSX changes to Certification/Dispatch and eFolder.

### CODE REVIEW

**Comment by KHarshawat-gov** [comment]
@mmlumba just a couple of fixes. 

- The go `« Close` link in the Special Issue Grant modal isn't aligned to the far left so it's flush with the text and the grey bar.
- Same with the `« Go back` link in the Cancel EP Establishment

**Comment by shanear** [comment]
Looks so awesome marian 💯💯💯💯💯

**Comment by mmlumba** [comment]
@KHarshawat-gov @lakohl here are the margin changes:
screen shot 2017-02-06 at 10 45 09 am
screen shot 2017-02-06 at 10 45 20 am

**Comment by lakohl** [comment]
@mmlumba 'Required' should aligned to the right end of the box and set in italic without parentheses.

**Comment by mmlumba** [comment]
@lakohl Does this work? Screenshot below:
screen shot 2017-02-06 at 11 13 16 am

**Comment by KHarshawat-gov** [comment]
@mmlumba no parenthesis around the word "required"

**Comment by lakohl** [comment]
Marian much better, but you can get rid of the parentheses!

**Comment by mmlumba** [comment]
@lakohl 
screen shot 2017-02-06 at 11 23 43 am

**Comment by mmlumba** [comment]
@astewarttistatech @kierachell Screenshots to test for validation in the dev/uat environments:
Certification/Dispatch:
screen shot 2017-02-03 at 2 38 10 pm
screen shot 2017-02-06 at 10 45 09 am
screen shot 2017-02-06 at 11 23 43 am
screen shot 2017-02-03 at 2 39 17 pm

eFolder:
screen shot 2017-02-03 at 2 40 06 pm

**Comment by kierachell** [comment]
screen shot 2017-02-09 at 20 00 37
After double checking with @lakohl and @Chingujo . The modal above does indeed need a red button

**Pull request merged**
